/* ============================================================================
 Name : 32.c
 Author : Simrath Kaur
 Description : Write a program to implement semaphore to protect any critical section.
a. rewrite the ticket number creation program using semaphore
b. protect shared memory from concurrent write access
c. protect multiple pseudo resources ( may be two) using counting semaphore
d. remove the created semaphore
============================================================================
*/
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <unistd.h>

// Function to create and initialize a semaphore
int createSemaphore(key_t key, int initialValue) {
    int semid = semget(key, 1, IPC_CREAT | 0666);
    if (semid == -1) {
        perror("semget");
        exit(1);
    }

    union semun {
        int val;
        struct semid_ds *buf;
        unsigned short *array;
    } sem_union;

    sem_union.val = initialValue;
    if (semctl(semid, 0, SETVAL, sem_union) == -1) {
        perror("semctl");
        exit(1);
    }

    return semid;
}

// Function to perform semaphore wait (P) operation
void semWait(int semid) {
    struct sembuf sem_op;
    sem_op.sem_num = 0;
    sem_op.sem_op = -1;
    sem_op.sem_flg = SEM_UNDO;
    if (semop(semid, &sem_op, 1) == -1) {
        perror("semop");
        exit(1);
    }
}

// Function to perform semaphore signal (V) operation
void semSignal(int semid) {
    struct sembuf sem_op;
    sem_op.sem_num = 0;
    sem_op.sem_op = 1;
    sem_op.sem_flg = SEM_UNDO;
    if (semop(semid, &sem_op, 1) == -1) {
        perror("semop");
        exit(1);
    }
}

int main() {
    key_t key = ftok("/tmp/ticket_key", 'a'); // Unique key for semaphores

    // Create and initialize a semaphore to protect the critical section
    int semaphore = createSemaphore(key, 1);

    int ticket = 0;
    int num_tickets = 10;

    for (int i = 0; i < num_tickets; i++) {
        semWait(semaphore); // Entry to the critical section
        ticket++;
        printf("Ticket %d generated by process %d\n", ticket, getpid());
        semSignal(semaphore); // Exit from the critical section
    }

    // Remove the semaphore
    if (semctl(semaphore, 0, IPC_RMID) == -1) {
        perror("semctl");
        exit(1);
    }

    return 0;
}

